Use new key line over linenumber.
Fixes where you can run into  the error below.

The puppet-lint deprecation

http://github.com/rodjek/puppet-lint/pull/540

has been merged into master.

According to

https://github.com/rodjek/puppet-lint/issues/539

it was meant to be added at version 3 but is now merged
with 2.0.2.

Thanks @Feandil for diagnosis.

```
rake aborted!
KeyError: key{linenumber} not found
/afs/cern.ch/user/s/straylen/.gem/ruby/bundler/gems/puppet-lint-32e93d43a3bf/lib/puppet-lint.rb:102:in
`%'
/afs/cern.ch/user/s/straylen/.gem/ruby/bundler/gems/puppet-lint-32e93d43a3bf/lib/puppet-lint.rb:102:in
`format_message'
/afs/cern.ch/user/s/straylen/.gem/ruby/bundler/gems/puppet-lint-32e93d43a3bf/lib/puppet-lint.rb:136:in
`block in report'
```