Adapt required rubocop config change
2 messages from rubocop in travis check:
.rubocop.yml: Lint/Eval has the wrong namespace - should be Security
Error: The `Style/MethodCallParentheses` cop has been renamed to `Style/MethodCallWithoutArgsParentheses`.

Both should be fixed with this commit.